# Generated by Django 2.1.5 on 2019-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images/blog/%Y/%m/%d', verbose_name='Image link'),
        ),
    ]
