# Generated by Django 2.1.5 on 2019-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190125_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/default.png', help_text='150x150px', null=True, upload_to='images/blog/%Y/%m/%d', verbose_name='Image link'),
        ),
    ]
